### ISSUE TITLE
TLS certificate

### ISSUE THREAD

**Issue by merkleID** [sindresorhus/capture-website#110]
Hi,

I'm trying to use capture-website to loop through the list created by a network-scan during my vulnerability assessments.
The problem is that, in LANs, appliances usually use a self-signed certificate and capture-website seems unable to ignore a certificate error and so to generate a valid screenshot of the webpage.

This is the typical error I get:

capture-website https://172.16.0.2 --output=1.png
Error: net::ERR_CERT_AUTHORITY_INVALID at https://172.16.0.2
    at navigate (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async internalCaptureWebsiteCore (file:///usr/local/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:281:2)
    at async internalCaptureWebsite (file:///usr/local/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:161:10)
    at async captureWebsite.file (file:///usr/local/lib/node_modules/capture-website-cli/node_modules/capture-website/index.js:438:21)
    at async file:///usr/local/lib/node_modules/capture-website-cli/cli.js:287:3

Any work-around for this?

thanks,
Luca

**Comment by sindresorhus** [comment]
You can pass in the `ignoreHTTPSErrors` option to the `launchOptions` option: https://pptr.dev/api/puppeteer.browserconnectoptions.ignorehttpserrors

**Comment by fiskhandlarn** [comment]
looks like you have to use `--launch-options='{"acceptInsecureCerts": true}'` nowadays: https://pptr.dev/api/puppeteer.connectoptions/#acceptinsecurecerts
