### ISSUE TITLE
Multiple screenshots example fails on .map function

### ISSUE THREAD

**Issue by EthanStrider** [sindresorhus/capture-website#17]
The example provided for capturing multiple screenshots:
```
const captureWebsite = require('capture-website');

const options = {
	width: 1920,
	height: 1000
};

const items = new Map([
	['https://sindresorhus.com', 'sindresorhus'],
	['https://github.com', 'github'],
	// …
]);

(async () => {
	await Promise.all(items.map(({url, filename}) => {
		return captureWebsite.file(url, `${filename}.png`, options);
	}));
})();
```

Fails with the following error:
```
(node:14336) UnhandledPromiseRejectionWarning: TypeError: items.map is not a function
    at /Users/user1/workspace/screenshots/attempt5/app.js:67:27
    at Object.<anonymous> (/Users/user1/workspace/screenshots/attempt5/app.js:70:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:14336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't have a solution yet, but I'll update when I do.

**Comment by EthanStrider** [comment]
Wow!  Thanks so much for the fix!  That was quick!
