### ISSUE TITLE
crashing on PDF files?

### ISSUE THREAD

**Issue by BananaAcid** [sindresorhus/capture-website#72]
I have no idea what to make out of it, but it seems to crash on PDFs
```
screenshot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_ABORTED at https://************/wp-content/uploads/2020/10/ABC-Februar-2018.pdf
    at navigate (/Users/nabil/Downloads/screenshot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async FrameManager.navigateFrame (/Users/nabil/Downloads/screenshot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/Users/nabil/Downloads/screenshot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/Users/nabil/Downloads/screenshot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async captureWebsite (/Users/nabil/Downloads/screenshot/node_modules/capture-website/index.js:233:2)
    at async Object.module.exports.file (/Users/nabil/Downloads/screenshot/node_modules/capture-website/index.js:367:21)
    at async mapper (file:///Users/nabil/Downloads/screenshot/screenshot-complete-domain.mjs:148:5)
    at async /Users/nabil/Downloads/screenshot/node_modules/p-map/index.js:57:22
```

**Comment by sindresorhus** [comment]
Puppeteer does not support PDFs: https://github.com/puppeteer/puppeteer/issues/2794

It is blocked by https://github.com/puppeteer/puppeteer/issues/299.
